name: pinkblue

description: I am Iron Man.

base-image: ghcr.io/secureblue/silverblue-main-hardened

image-version: latest

modules:
  - type: files
    files:
      - source: system/usr
        destination: /usr
      - source: system/etc
        destination: /etc
  - from-file: common/packages.yml
  - type: gschema-overrides
    include:
      - zz2-pinkblue.gschema.override
